# Generated by Django 4.2.4 on 2025-11-02 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_cart_cartitem_memberpatient_remove_test_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_bookings', to='app.patient')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.timeslot')),
                ('tests', models.ManyToManyField(related_name='bookings', to='app.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestBookingPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_self', models.BooleanField(default=False)),
                ('attendance', models.BooleanField(default=False)),
                ('report', models.FileField(blank=True, null=True, upload_to='test_reports/')),
                ('report_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready')], default='pending', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='test_booking.testbooking')),
                ('member_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.memberpatient')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
