# Generated by Django 5.2.6 on 2025-10-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='available',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booked_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='max_patients',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of patients for this slot. Leave empty if unlimited.', null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='BOOKED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.patient')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.timeslot')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('timeslot', 'patient')},
            },
        ),
    ]
