# Generated by Django 5.2.6 on 2025-09-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_branch_test_med_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='med_branch',
            new_name='branch',
        ),
    ]
