# Generated by Django 5.2.6 on 2025-10-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_timeslot_available_timeslot_booked_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='booked_slots',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='specialization',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='max_patients',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
