# Generated by Django 5.2.6 on 2025-10-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_timeslot_booked_slots_timeslot_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulttimeslot',
            name='available_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulttimeslot',
            name='booked_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='available_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booked_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.timeslot')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
