# Generated by Django 5.2.6 on 2025-10-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_alter_test_testid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('slotid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_patients', models.PositiveIntegerField(default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='app.test')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('test', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
