# Generated by Django 5.2.6 on 2025-10-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
    ]
