# Generated by Django 5.2.6 on 2025-10-06 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_test_available_time_remove_test_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pid',
        ),
    ]
