# Generated by Django 5.2.6 on 2025-10-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_patient_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
