# Generated by Django 5.2.6 on 2025-10-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_patient_address_remove_patient_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='slotid',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
