# Generated by Django 5.2.6 on 2025-10-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_timeslot_slotid_timeslot_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='Package',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='branch',
            new_name='package',
        ),
    ]
