# Generated by Django 5.2.6 on 2025-10-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_branch_package_rename_branch_test_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='testid',
        ),
    ]
